### ISSUE TITLE
Robuustheid: beveiliging tegen dubbel downloadjobs uitvoeren

### ISSUE THREAD

**Issue by robstek** [IDgis/download-tool#84]
Het is mogelijk dat download jobs die door de processor uit de queue zijn gehaald er in blijven staan. Dezelfde job kan dan vervolgens weer uitgevoerd worden.
Een check kan bijv worden uitgevoerd in de feedback provider.

**Comment by copierrj** [comment]
oplossingsrichting: referentiële integriteit tussen request en response tabellen in de database met daarbij de contraint dat we geen tweede response bij een request accepteren.
